### ISSUE TITLE
Make it easier to use a custom backend

### ISSUE THREAD

**Issue by SpaceK33z** [CodeYellowBV/mobx-binder#5]
It should be a bit easier to use a custom backend. This package is clearly suited towards Binder, our Python backend, but we can at least provide hooks to customize the backend handling.

**Comment by SpaceK33z** [comment]
This is related to #2.

**Comment by JasperStam** [comment]
It would help a lot if we can override the `request` instance that models and stores use.

**Comment by SpaceK33z** [comment]
I worked on this Sunday. You can use the separate-api branch if you want this. It is essentially finished.
